<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class BagItemsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('bag_items')->insert([
            [
                'bags_categories_id' => DB::table('bags_categories')->inRandomOrder()->value('id') ?? 1,
                'title' => Str::title('title') . '_' . Str::random(5),
                'price' => 'Sample_' . Str::random(5),
                'image' => collect(['https://images.unsplash.com/photo-1498050108023-c5249f4df085','https://images.unsplash.com/photo-1461747823400-487cf1852d7e','https://images.unsplash.com/photo-1504639725590-34d0984388bd'])->random(),
                'currency' => collect(['ريال','دولار','جنيه مصري'])->random(),
                'rating' => 'Sample_' . Str::random(5),
                'desc' => Str::title('desc') . '_' . Str::random(5),
                'Whose' => 'Sample_' . Str::random(5),
                'what_will_you_get' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bags_categories_id' => DB::table('bags_categories')->inRandomOrder()->value('id') ?? 1,
                'title' => Str::title('title') . '_' . Str::random(5),
                'price' => 'Sample_' . Str::random(5),
                'image' => collect(['https://images.unsplash.com/photo-1498050108023-c5249f4df085','https://images.unsplash.com/photo-1461747823400-487cf1852d7e','https://images.unsplash.com/photo-1504639725590-34d0984388bd'])->random(),
                'currency' => collect(['ريال','دولار','جنيه مصري'])->random(),
                'rating' => 'Sample_' . Str::random(5),
                'desc' => Str::title('desc') . '_' . Str::random(5),
                'Whose' => 'Sample_' . Str::random(5),
                'what_will_you_get' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bags_categories_id' => DB::table('bags_categories')->inRandomOrder()->value('id') ?? 1,
                'title' => Str::title('title') . '_' . Str::random(5),
                'price' => 'Sample_' . Str::random(5),
                'image' => collect(['https://images.unsplash.com/photo-1498050108023-c5249f4df085','https://images.unsplash.com/photo-1461747823400-487cf1852d7e','https://images.unsplash.com/photo-1504639725590-34d0984388bd'])->random(),
                'currency' => collect(['ريال','دولار','جنيه مصري'])->random(),
                'rating' => 'Sample_' . Str::random(5),
                'desc' => Str::title('desc') . '_' . Str::random(5),
                'Whose' => 'Sample_' . Str::random(5),
                'what_will_you_get' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bags_categories_id' => DB::table('bags_categories')->inRandomOrder()->value('id') ?? 1,
                'title' => Str::title('title') . '_' . Str::random(5),
                'price' => 'Sample_' . Str::random(5),
                'image' => collect(['https://images.unsplash.com/photo-1498050108023-c5249f4df085','https://images.unsplash.com/photo-1461747823400-487cf1852d7e','https://images.unsplash.com/photo-1504639725590-34d0984388bd'])->random(),
                'currency' => collect(['ريال','دولار','جنيه مصري'])->random(),
                'rating' => 'Sample_' . Str::random(5),
                'desc' => Str::title('desc') . '_' . Str::random(5),
                'Whose' => 'Sample_' . Str::random(5),
                'what_will_you_get' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bags_categories_id' => DB::table('bags_categories')->inRandomOrder()->value('id') ?? 1,
                'title' => Str::title('title') . '_' . Str::random(5),
                'price' => 'Sample_' . Str::random(5),
                'image' => collect(['https://images.unsplash.com/photo-1498050108023-c5249f4df085','https://images.unsplash.com/photo-1461747823400-487cf1852d7e','https://images.unsplash.com/photo-1504639725590-34d0984388bd'])->random(),
                'currency' => collect(['ريال','دولار','جنيه مصري'])->random(),
                'rating' => 'Sample_' . Str::random(5),
                'desc' => Str::title('desc') . '_' . Str::random(5),
                'Whose' => 'Sample_' . Str::random(5),
                'what_will_you_get' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bags_categories_id' => DB::table('bags_categories')->inRandomOrder()->value('id') ?? 1,
                'title' => Str::title('title') . '_' . Str::random(5),
                'price' => 'Sample_' . Str::random(5),
                'image' => collect(['https://images.unsplash.com/photo-1498050108023-c5249f4df085','https://images.unsplash.com/photo-1461747823400-487cf1852d7e','https://images.unsplash.com/photo-1504639725590-34d0984388bd'])->random(),
                'currency' => collect(['ريال','دولار','جنيه مصري'])->random(),
                'rating' => 'Sample_' . Str::random(5),
                'desc' => Str::title('desc') . '_' . Str::random(5),
                'Whose' => 'Sample_' . Str::random(5),
                'what_will_you_get' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bags_categories_id' => DB::table('bags_categories')->inRandomOrder()->value('id') ?? 1,
                'title' => Str::title('title') . '_' . Str::random(5),
                'price' => 'Sample_' . Str::random(5),
                'image' => collect(['https://images.unsplash.com/photo-1498050108023-c5249f4df085','https://images.unsplash.com/photo-1461747823400-487cf1852d7e','https://images.unsplash.com/photo-1504639725590-34d0984388bd'])->random(),
                'currency' => collect(['ريال','دولار','جنيه مصري'])->random(),
                'rating' => 'Sample_' . Str::random(5),
                'desc' => Str::title('desc') . '_' . Str::random(5),
                'Whose' => 'Sample_' . Str::random(5),
                'what_will_you_get' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bags_categories_id' => DB::table('bags_categories')->inRandomOrder()->value('id') ?? 1,
                'title' => Str::title('title') . '_' . Str::random(5),
                'price' => 'Sample_' . Str::random(5),
                'image' => collect(['https://images.unsplash.com/photo-1498050108023-c5249f4df085','https://images.unsplash.com/photo-1461747823400-487cf1852d7e','https://images.unsplash.com/photo-1504639725590-34d0984388bd'])->random(),
                'currency' => collect(['ريال','دولار','جنيه مصري'])->random(),
                'rating' => 'Sample_' . Str::random(5),
                'desc' => Str::title('desc') . '_' . Str::random(5),
                'Whose' => 'Sample_' . Str::random(5),
                'what_will_you_get' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bags_categories_id' => DB::table('bags_categories')->inRandomOrder()->value('id') ?? 1,
                'title' => Str::title('title') . '_' . Str::random(5),
                'price' => 'Sample_' . Str::random(5),
                'image' => collect(['https://images.unsplash.com/photo-1498050108023-c5249f4df085','https://images.unsplash.com/photo-1461747823400-487cf1852d7e','https://images.unsplash.com/photo-1504639725590-34d0984388bd'])->random(),
                'currency' => collect(['ريال','دولار','جنيه مصري'])->random(),
                'rating' => 'Sample_' . Str::random(5),
                'desc' => Str::title('desc') . '_' . Str::random(5),
                'Whose' => 'Sample_' . Str::random(5),
                'what_will_you_get' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bags_categories_id' => DB::table('bags_categories')->inRandomOrder()->value('id') ?? 1,
                'title' => Str::title('title') . '_' . Str::random(5),
                'price' => 'Sample_' . Str::random(5),
                'image' => collect(['https://images.unsplash.com/photo-1498050108023-c5249f4df085','https://images.unsplash.com/photo-1461747823400-487cf1852d7e','https://images.unsplash.com/photo-1504639725590-34d0984388bd'])->random(),
                'currency' => collect(['ريال','دولار','جنيه مصري'])->random(),
                'rating' => 'Sample_' . Str::random(5),
                'desc' => Str::title('desc') . '_' . Str::random(5),
                'Whose' => 'Sample_' . Str::random(5),
                'what_will_you_get' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}