<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'name' => Str::title('name') . '_' . Str::random(5),
                'email' => 'user_' . Str::lower(Str::random(8)) . '_0@example.com',
                'phone' => '01' . rand(100, 999) . rand(1000, 9999) . 0,
                'country_code' => Str::title('country_code') . '_' . Str::random(5),
                'is_active' => 0,
                'email_verified_at' => now(),
                'remember_token' => Str::title('remember_token') . '_' . Str::random(5),
                'role' => collect(['user', 'super_admin'])->random(),
                'social_type' => collect(['google', 'apple', 'facebook'])->random(),
                'social_id' => 1545,
                'password' => bcrypt('password'),
                'last_login_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => Str::title('name') . '_' . Str::random(5),
                'email' => 'user_' . Str::lower(Str::random(8)) . '_1@example.com',
                'phone' => '01' . rand(100, 999) . rand(1000, 9999) . 1,
                'country_code' => Str::title('country_code') . '_' . Str::random(5),
                'is_active' => 0,
                'email_verified_at' => now(),
                'remember_token' => Str::title('remember_token') . '_' . Str::random(5),
                'role' => collect(['user', 'super_admin'])->random(),
                'social_type' => collect(['google', 'apple', 'facebook'])->random(),
                'social_id' => 15452,
                'password' => bcrypt('password'),
                'last_login_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => Str::title('name') . '_' . Str::random(5),
                'email' => 'user_' . Str::lower(Str::random(8)) . '_2@example.com',
                'phone' => '01' . rand(100, 999) . rand(1000, 9999) . 2,
                'country_code' => Str::title('country_code') . '_' . Str::random(5),
                'is_active' => 0,
                'email_verified_at' => now(),
                'remember_token' => Str::title('remember_token') . '_' . Str::random(5),
                'role' => collect(['user', 'super_admin'])->random(),
                'social_type' => collect(['google', 'apple', 'facebook'])->random(),
                'social_id' => 15453,
                'password' => bcrypt('password'),
                'last_login_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => Str::title('name') . '_' . Str::random(5),
                'email' => 'user_' . Str::lower(Str::random(8)) . '_3@example.com',
                'phone' => '01' . rand(100, 999) . rand(1000, 9999) . 3,
                'country_code' => Str::title('country_code') . '_' . Str::random(5),
                'is_active' => 1,
                'email_verified_at' => now(),
                'remember_token' => Str::title('remember_token') . '_' . Str::random(5),
                'role' => collect(['user', 'super_admin'])->random(),
                'social_type' => collect(['google', 'apple', 'facebook'])->random(),
                'social_id' => 15454,
                'password' => bcrypt('password'),
                'last_login_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => Str::title('name') . '_' . Str::random(5),
                'email' => 'user_' . Str::lower(Str::random(8)) . '_4@example.com',
                'phone' => '01' . rand(100, 999) . rand(1000, 9999) . 4,
                'country_code' => Str::title('country_code') . '_' . Str::random(5),
                'is_active' => 0,
                'email_verified_at' => now(),
                'remember_token' => Str::title('remember_token') . '_' . Str::random(5),
                'role' => collect(['user', 'super_admin'])->random(),
                'social_type' => collect(['google', 'apple', 'facebook'])->random(),
                'social_id' => 15455,
                'password' => bcrypt('password'),
                'last_login_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => Str::title('name') . '_' . Str::random(5),
                'email' => 'user_' . Str::lower(Str::random(8)) . '_5@example.com',
                'phone' => '01' . rand(100, 999) . rand(1000, 9999) . 5,
                'country_code' => Str::title('country_code') . '_' . Str::random(5),
                'is_active' => 1,
                'email_verified_at' => now(),
                'remember_token' => Str::title('remember_token') . '_' . Str::random(5),
                'role' => collect(['user', 'super_admin'])->random(),
                'social_type' => collect(['google', 'apple', 'facebook'])->random(),
                'social_id' => 15456,
                'password' => bcrypt('password'),
                'last_login_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => Str::title('name') . '_' . Str::random(5),
                'email' => 'user_' . Str::lower(Str::random(8)) . '_6@example.com',
                'phone' => '01' . rand(100, 999) . rand(1000, 9999) . 6,
                'country_code' => Str::title('country_code') . '_' . Str::random(5),
                'is_active' => 0,
                'email_verified_at' => now(),
                'remember_token' => Str::title('remember_token') . '_' . Str::random(5),
                'role' => collect(['user', 'super_admin'])->random(),
                'social_type' => collect(['google', 'apple', 'facebook'])->random(),
                'social_id' => 15457,
                'password' => bcrypt('password'),
                'last_login_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => Str::title('name') . '_' . Str::random(5),
                'email' => 'user_' . Str::lower(Str::random(8)) . '_7@example.com',
                'phone' => '01' . rand(100, 999) . rand(1000, 9999) . 7,
                'country_code' => Str::title('country_code') . '_' . Str::random(5),
                'is_active' => 1,
                'email_verified_at' => now(),
                'remember_token' => Str::title('remember_token') . '_' . Str::random(5),
                'role' => collect(['user', 'super_admin'])->random(),
                'social_type' => collect(['google', 'apple', 'facebook'])->random(),
                'social_id' => 15458,
                'password' => bcrypt('password'),
                'last_login_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => Str::title('name') . '_' . Str::random(5),
                'email' => 'user_' . Str::lower(Str::random(8)) . '_8@example.com',
                'phone' => '01' . rand(100, 999) . rand(1000, 9999) . 8,
                'country_code' => Str::title('country_code') . '_' . Str::random(5),
                'is_active' => 0,
                'email_verified_at' => now(),
                'remember_token' => Str::title('remember_token') . '_' . Str::random(5),
                'role' => collect(['user', 'super_admin'])->random(),
                'social_type' => collect(['google', 'apple', 'facebook'])->random(),
                'social_id' => 15459,
                'password' => bcrypt('password'),
                'last_login_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => Str::title('name') . '_' . Str::random(5),
                'email' => 'user_' . Str::lower(Str::random(8)) . '_9@example.com',
                'phone' => '01' . rand(100, 999) . rand(1000, 9999) . 9,
                'country_code' => Str::title('country_code') . '_' . Str::random(5),
                'is_active' => 1,
                'email_verified_at' => now(),
                'remember_token' => Str::title('remember_token') . '_' . Str::random(5),
                'role' => collect(['user', 'super_admin'])->random(),
                'social_type' => collect(['google', 'apple', 'facebook'])->random(),
                'social_id' => 154511,
                'password' => bcrypt('password'),
                'last_login_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
