/**
 * Auto-generated fields for Branch
 * Generated at: 2026-04-15 09:47:38
 */
export const BranchFields = [
  { 
    key: "id", 
    label: "Id", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Id",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: true,
    options: null
  },
  { 
    key: "user_id", 
    label: "User Id", 
    type: "select", 
    cell_type: "relation",
    display_field: "user.name",
    required: 1, 
    placeholder: "Enter User Id",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: true,
    endpoint: 'users',
    relation_fields: 'id,name',
    options: { label: 'name', value: 'id' }
  },
  { 
    key: "title", 
    label: "Title", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Title",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  { 
    key: "address", 
    label: "Address", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Address",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  { 
    key: "mobile", 
    label: "Mobile", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Mobile",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  { 
    key: "lat", 
    label: "Lat", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 0, 
    placeholder: "Enter Lat",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  { 
    key: "lng", 
    label: "Lng", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 0, 
    placeholder: "Enter Lng",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  { 
    key: "created_at", 
    label: "Created At", 
    type: "date", 
    cell_type: "date",
    display_field: null,
    required: 0, 
    placeholder: "Enter Created At",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: false,
    options: null
  },
  { 
    key: "updated_at", 
    label: "Updated At", 
    type: "date", 
    cell_type: "date",
    display_field: null,
    required: 0, 
    placeholder: "Enter Updated At",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: false,
    options: null
  }
];