/**
 * Auto-generated fields for Service
 * Generated at: 2026-04-22 14:31:45
 */
export const ServiceFields = [
  { 
    key: "id", 
    label: "Id", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Id",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: true,
    options: null
  },
  { 
    key: "user_id", 
    label: "User Id", 
    type: "select", 
    cell_type: "relation",
    display_field: "user.name",
    required: 0, 
    placeholder: "Enter User Id",
    searchable: false,
    filterable: true,
    sortable: true,
    table_show: false,
    form_show: true,
    endpoint: 'users',
    relation_fields: 'id,name',
    options: { label: 'name', value: 'id' }
  },
  { 
    key: "category_id", 
    label: "Category Id", 
    type: "select", 
    cell_type: "relation",
    display_field: "category.name",
    required: 0, 
    placeholder: "Enter Category Id",
    searchable: false,
    filterable: true,
    sortable: true,
    table_show: false,
    form_show: true,
    endpoint: 'categories',
    relation_fields: 'id,name',
    options: { label: 'name', value: 'id' }
  },
  { 
    key: "city_id", 
    label: "City Id", 
    type: "select", 
    cell_type: "relation",
    display_field: "city.name",
    required: 0, 
    placeholder: "Enter City Id",
    searchable: false,
    filterable: true,
    sortable: true,
    table_show: false,
    form_show: true,
    endpoint: 'cities',
    relation_fields: 'id,name',
    options: { label: 'name', value: 'id' }
  },
  { 
    key: "title", 
    label: "Title", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Title",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  { 
    key: "desc", 
    label: "Desc", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Desc",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  { 
    key: "image", 
    label: "Image", 
    type: "file", 
    cell_type: "image",
    display_field: null,
    required: 1, 
    placeholder: "Enter Image",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  { 
    key: "price", 
    label: "Price", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Price",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  { 
    key: "created_at", 
    label: "Created At", 
    type: "date", 
    cell_type: "date",
    display_field: null,
    required: 0, 
    placeholder: "Enter Created At",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: false,
    options: null
  },
  { 
    key: "updated_at", 
    label: "Updated At", 
    type: "date", 
    cell_type: "date",
    display_field: null,
    required: 0, 
    placeholder: "Enter Updated At",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: false,
    options: null
  }
];